### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by sanbuddhacharyas** [tobias-kirschstein/nersemble#1]
Thank you for sharing your code. I just wanted to know if you have pre-trained weight for nersemble. Thank you. Please do share it if you have a pre-trained model.

**Comment by tobias-kirschstein** [comment]
Hi San,

Thank you for your interest in the NeRSemble project.
We just released the trained models for the 10 multi-view video sequences we used in the paper.  
You can find instructions on downloading the weights and rendering a video from the model in the [README](https://github.com/tobias-kirschstein/nersemble) file.

Best,
Tobias
