### ISSUE TITLE
Resume Training from Checkpoint

### ISSUE THREAD

**Issue by KaneLindsay** [tobias-kirschstein/nersemble#10]
Is there functionality to load a previous model checkpoint to continue training?

**Comment by tobias-kirschstein** [comment]
Hi,
thank you for your interest in our work.
I added a `--resume_run` flag to the train script. If provided, it will try to load the latest checkpoint from the specified run.
For example `--resume_run NERS-9018` would continue training the pretrained model for participant ID 18.
If you wish to resume a different checkpoint than the latest, you can use the `--resume_checkpoint` flag.
Hope this helps, and tell me if you encounter any issues. I haven't tested this extensively.

**Comment by KaneLindsay** [comment]
Thank you for your prompt response, I can now successfully load checkpoints for training.
