### ISSUE TITLE
Matting masks for free part?

### ISSUE THREAD

**Issue by summertight** [tobias-kirschstein/nersemble#6]
Thank you for your excellent work. Could you please provide the alpha maps for the free parts? All emotional segments, with the exception of this particular part, already have their alpha maps for background removal. In case they are not available, could we obtain the background images for each camera?

Best regards,

**Comment by tobias-kirschstein** [comment]
Hi,

Thank you for your interest in the NeRSemble dataset.
Could you clarify which archive you mean when you say "free parts"?
I checked the `nersemble_124_FREE.zip` and that one contains the alpha maps in the `alpha_map-73fps` subfolder.

If you need matting masks for sequences from view 2 or view 3, you need to calculate them yourself. You find the corresponding empty background images in the `sequence_BACKGROUND_part-1.zip` archive.

**Comment by summertight** [comment]
Thank you for your quick response.
I have meant the view 3's FREE parts.
Have a good day.

Best regards,

**Comment by Vincento-Wang** [comment]
same problem , I wonder how to get the alpha map ?
