### ISSUE TITLE
How to do color correction in other sequences?

### ISSUE THREAD

**Issue by AtlantixJJ** [tobias-kirschstein/nersemble#8]
There is only color correction on the 10 sequences used in the paper while for the majority of other data, there is no such file. 

I found in your paper that color correction involves a quite complex procedure, including face segmentation and optimal transport solving, which appears to be hard to reproduce.

I wonder if you could release (or point to) the code of doing such preprocessing, or release the correction data for the rest of the data?

Thank you very much.

**Comment by tobias-kirschstein** [comment]
Hi,

thanks for your interest in the NeRSemble dataset.   
We added the color correction for all of the participants now to the dataset.   
You can find the download link in the `README.md` file (You have to download the `README.md` again to see the changes).  

The `color_correction.zip` file contains affine color transformation matrices (following the procedure described in the NeRSemble paper) for each participant and each of the 16 cameras.  
To apply the color correction to an image of person `$ID` and camera `$SERIAL`, the following code may be used:
```python
affine_color_transform = np.load('color_correction/$ID/$SERIAL.npy')
image = image @ affine_color_transform[:3, :3] + affine_color_transform[np.newaxis, :3, 3]
image = np.clip(image, 0, 1)
```

Hope this helps
