### ISSUE TITLE
Coordinate System of Camera Matrix

### ISSUE THREAD

**Issue by JeremyCJM** [tobias-kirschstein/nersemble#9]
Hi authors, in your dataset, the camera extrinsics are stored in camera_params.json. Could you share which coordinate system are those matrices in? Are they in OpenGL or OpenCV or Pytorch3D style?

**Comment by JeremyCJM** [comment]
I just found the answer in [this file](https://github.com/tobias-kirschstein/nersemble/blob/master/src/nersemble/nerfstudio/dataparser/nersemble_dataparser.py#L253). It is OpenCV coordinate system. Thanks!

**Comment by tobias-kirschstein** [comment]
Yes, it is OpenCV. We also describe it in the README:

> Extrinsics are given in `world2cam` format with the camera space following OpenCV convention (x -> right, y -> down, z -> forward).  
> The world space is metric.  
> The intrinsics are given wrt to the full image resolution (3208 x 2200) and are shared for all 16 cameras.
